[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "paleontologist"
authors = [{name = "Arianne Bercowsky Rama", email = "bercowskya@gmail.com"}]
dynamic = ["version", "description"]
